### PR TITLE
N°4703 - Add Dutch translations to new origins

### PR DESCRIPTION
**Pull request by Hipska**
Adds Dutch translations to #341

### CODE REVIEW

**Review by piRGoif — APPROVED** [review]

**Comment by piRGoif** [comment]
Note : origin attribute is defined on each children classes

**Comment by Hipska** [comment]
@piRGoif I did exactly the same as original #341.

**Comment by piRGoif** [comment]
> I did exactly the same as original

Yes :) I didn't recall this attribute was defined in children classes, so I just put a note so everyone won't spent time figuring why the translations are defined at the children class level :)

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
@piRGoif as this is just about new dict. entries, maybe we can move it directly to functional review as we already both reviewed it. What do you think?

**Review by steffunky — APPROVED** [review]

**Comment by Molkobain** [comment]
Accepted during functional review.

**Pull request merged**
