### PR TITLE
Feature/merge 3 0 develop

### PR DESCRIPTION
**Pull request by bdalsass**

### CODE REVIEW

**Comment by Hipska** [comment]
Whoa, why not do a regular merge like was usually done in the past? This misses a lot of historical information..

**Comment by piRGoif** [comment]
I agree :)
Benjamin tried something, this is under discussion

**Comment by Hipska** [comment]
Okay, but it's already merged 😕

**Comment by piRGoif** [comment]
The PR is merged yes but in a git sense there are no merge between support/3.0 and develop : trying to merge right now produces dozens of conflicts...
We'll figure all of this out and keep everyone posted here.

**Comment by Hipska** [comment]
Yes there are merges between support/3.0 and develop. For example one you did in 3d541b2a2da36323cd74c1aa0ec614c13b9b415a.

**Comment by piRGoif** [comment]
I meant usually we did regular merge commits like the one you pointed out.
This PR adds a commit in develop but the branches remained with unmerged changes anyway...

**Pull request merged**
