### PR TITLE
🎨 Fix the filter icon on Data model page

### PR DESCRIPTION
**Pull request by Hipska**
For some unknown reason, the icon used to run a filter query on the datamodel page was [JUNO](https://unicode-table.com/en/26B5/). Sadly this icon does not work on macOS and an empty square is shown, so I replaced it with the 🔎 emoji.

If you find any better icon, please let me know.

### CODE REVIEW

**Comment by Molkobain** [comment]
@steffunky what was the original intention?

**Comment by steffunky** [comment]
I tried to find an icon that looked like a "filter" icon, but I guess it's really a random Unicode char.
The magnifying glass emoji is okay for me, but maybe a FontAwesome icon would be better as we could style it to look like an external link (as the "Filter" text next to it isn't clickable and it may not be obvious that the emoji is)?

**Comment by Molkobain** [comment]
+1 on the FontAwesome icon, it allows us to have a consistent rendering on all platforms and it can be stylized as Stephen said (_Note: Please use a dedicated span tag within the anchor._)

**Comment by Hipska** [comment]
I agree to have FA icon as well..

**Comment by Molkobain** [comment]
Once done, I don't see any reason no to merge this 😁

**Comment by Hipska** [comment]
Do you expect me to craft an FA icon or will someone provide it?

**Comment by Molkobain** [comment]
You can use this one : https://fontawesome.com/icons/search?style=solid
(Spoiler : `<i class="fas fa-search"></i>`)

**Comment by Hipska** [comment]
Done!

**Comment by Molkobain** [comment]
Great thanks!

**Review by Molkobain — APPROVED** [review]

**Pull request merged**
