### PR TITLE
🌐 Update chinese dictionaries for 3.0

### PR DESCRIPTION
**Pull request by purplegrape**
better and more chinese translations

### CODE REVIEW

**Comment by purplegrape** [comment]
c623e72  has already been commited last time , so  it can be ignored

**Comment by piRGoif** [comment]
Hi @purplegrape, thanks for your contribution
I'm confused, why are you pushing a commit already merged ?
Also, your branch has conflicts with develop's head (might be caused by the said commit), can you rebase and resolve those conflicts so we can review your PR ?

**Comment by purplegrape** [comment]
I'm confused too, 
I am using github desktop client ,it seems can't not do rebase action
I  have to delete my own branch ,then fork a fresh new one

**Comment by piRGoif** [comment]
Ok, thanks

**Pull request closed without merging**
