### PR TITLE
Update nl.dictionary.itop.ui.php

### PR DESCRIPTION
**Pull request by Hipska**

### CODE REVIEW

**Review by piRGoif — DISMISSED** [review]

**Comment by piRGoif** [comment]
Ok for me, @jbostoen are you ok with this ?

We prefer not to touch the upcoming 2.7.0, for now your commit is based on the future 2.8.0 branch, is this what you had in mind Thomas ? Maybe this could be included in 2.7.1... What would you prefer ?

**Comment by Hipska** [comment]
If possible, include this in 2.7.1. Thanks!

**Comment by piRGoif** [comment]
All right !
We need to finish 2.7.0 first, should be ok by the end of next week. Then we'll be able to merge your PR to the master branch : I'll ask you then to rebase.
Will keep you informed...

Also I'm waiting for Jeffrey's opinion on your modification O:)

**Comment by Hipska** [comment]
Do I create a second PR based on master branch in the meantime?

**Comment by piRGoif** [comment]
For now there are no branches available for 2.7.1 developments, it will be master after the merge of release/2.7.0 to both master and develop. When this will be done, we'll just have to rebase your PR branch to the master branch. Should be no need to create a new branch and PR, and as your modifications does not impact lots of files we shouldn't have any merge conflict.

**Comment by jbostoen** [comment]
Okay for me :)

**Comment by piRGoif** [comment]
Thanks Jeffrey and Thomas !
I'm keeping the PR open, as soon as 2.7.0 will be merged I'll get back to you Thomas.

**Comment by piRGoif** [comment]
Hello, 
We are ready to accept commits for the next 2.7.1 now.
Can you rebase your modifications on our master branch ? You will need to pull from upstream first...

**Comment by Hipska** [comment]
Can I do that from GitHub UI? Can't find it.

And now there seems to be merg conflicts as wel.. The constants are now in the string.

Do I create a patch for 2.7 branch and also for develop?

**Comment by piRGoif** [comment]
>> Can you rebase your modifications on our master branch ?
>
> Can I do that from GitHub UI? Can't find it.

Wooops sorry, the master branch was replaced by the support/2.7 branch.
Rebase on this one.

> Do I create a patch for 2.7 branch and also for develop?

No, only on support/2.7, and this will be merged later on in develop : we are doing such merge regularly.

**Comment by Hipska** [comment]
Yes, can I rebased From Github or does it mean I do it on my PC manually?

**Comment by piRGoif** [comment]
I would recommend to rebase manually using git commands instead of doing it on the GitHub website, as I tried to do it myself this way and the results were not nice :/

**Comment by Hipska** [comment]
Merge conflict solved 😉

**Review by piRGoif — APPROVED** [review]

**Comment by piRGoif** [comment]
I changed the base branch as it was still develop instead of support/2.7.
Ok to merge !

**Pull request merged**
