### PR TITLE
Show real next backup date

### PR DESCRIPTION
**Pull request by Hipska**
- Get the next backup date from what is scheduled in the background task.
- Show different message if cron is not running.

### CODE REVIEW

**Comment by piRGoif** [comment]
Thanks Hipska ! Seems nice to me, but I think products team review is needed.
Before that, can you send a screenshot of the 2 possible messages ?

**Comment by Hipska** [comment]
The first one is exactly the same as what is currently in use, but with a more correct date in some cases.

I will put a screenshot of the case when cron is not running soon..

**Comment by Hipska** [comment]
image

**Comment by piRGoif** [comment]
Many thanks Thomas !
The PR is now ready for review with the products team !

**Comment by piRGoif** [comment]
Products team is ok with this PR. 
It will then be reviewed by the dev team.

**Comment by piRGoif** [comment]
> The first one is exactly the same as what is currently in use, but with a more correct date in some cases.

Could you give some examples please ?

**Comment by Hipska** [comment]
For example when cron is not running anymore (the date will then be in history, that should indicate it will be done as soon as the cron is restarted)

Another example, is when you just changed the backup configuration. (Before you would see the new datetime according the settings, but that's not correct since it will first do a last backup according to previous settings)

**Comment by piRGoif** [comment]
Dev team is ok to integrate this code !
But your PR is based on support/2.7, and I'm not sure everyone is OK to merge to this branch... I've just asked, I'll update the PR as soon as I'll get the answer !

**Comment by Hipska** [comment]
Yes, since I wanted it to be fixed in next 2.7 release.

**Comment by piRGoif** [comment]
Thanks !
I'll keep you posted after the product team review

**Comment by Hipska** [comment]
Any update? Will it be included in next release?

**Comment by piRGoif** [comment]
A review with the product team is planned at the end of next week (for various reasons, it was hard to find a calendar slot...)
This PR will be in the meetting's agenda !

**Comment by piRGoif** [comment]
Hello,
Product team is OK to integrate this but only for 3.0.0.
Can you rebase on the develop branch please ?

**Comment by Hipska** [comment]
Hi, I think I have succeeded with that rebase..

**Comment by piRGoif** [comment]
Yes, perfect ! Ready to merge !

**Pull request merged**
