### PR TITLE
:bug: N°4662 - Fix broken display of portal service catalog when a description is defined for a service (Service Provider module)

### PR DESCRIPTION
**Pull request by alally**
In September a change was made to the list, mosaic and tree twigs for rendering the service catalog. It caused the rendering of the service catalog to throw an exception when a description was filled in for a service which blocked the entire rendering of the catalog.

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello @alally can you provide examples that caused the issue please?

**Comment by alally** [comment]
Reproduction steps from a fresh install of the 3.0.0 release.

1. Create a service family called "helpdesk"
2. Create a service called "identity management"
3. Add a description to the "identity management" service
4. Create a "Identity Management" service subcategory of "Password Reset" 
5. Assign the service to a customer contract.
6. Attempt to open the portal as that customer.

For me within Firefox and Edge the loading of the service catalog is stuck spinning and the below is an error logged in the developer console. The "Request service pertaining to someone's online identity" part is the description I put into the Identity Management service. Though it occurs anytime the field is not blank.  

```
Uncaught Error: Syntax error, unrecognized expression: Request service pertaining to someone&#039;s online identity
    at Function.se.error (jquery.min.js?itopversion=3.0.0:2:13606)
    at se.tokenize (jquery.min.js?itopversion=3.0.0:2:21617)
    at se.select (jquery.min.js?itopversion=3.0.0:2:22444)
    at Function.se (jquery.min.js?itopversion=3.0.0:2:7089)
    at Function.s.find (jquery-migrate.prod.min.js?itopversion=3.0.0:2:2121)
    at S.fn.init.find (jquery.min.js?itopversion=3.0.0:2:25014)
    at s.fn.init.S.fn.init (jquery.min.js?itopversion=3.0.0:2:25503)
    at new s.fn.init (jquery-migrate.prod.min.js?itopversion=3.0.0:2:1718)
    at S (jquery.min.js?itopversion=3.0.0:2:1024)
    at _ (list?exec_module=itop-portal-base&exec_page=index.php&portal_id=itop-portal:536:45)
```

**Comment by Molkobain** [comment]
Thanks, we'll take a look at it during the next PR review in 2 weeks. I'll keep you posted.

Edit: This might be related to internal bug N°4662

**Comment by Molkobain** [comment]
Hello @alally ,

The fix you made is actually to revert the code to its previous state. That change was made to avoid display of empty tooltips on elements.

Depending on which setup option you choose during the setup (Service management for provider or Service management for enterprise), the "description" attribute has a different type. The actual fix would be to find a way to handle correctly the different attribute types in that case.

Do you feel like investigating this?

**Comment by alally** [comment]
@Molkobain that is correct, I was reverting what was done because it broke functionality completely. I was configured for Service Management for Provider which was affected negatively by the code change. I did not validate against the other deployment model. 

I'm not certain I will personally have the time to resolve the issue with the enterprise side of it. I noticed the issue while trialing/playing with the software and figured I would give back and submit a pull request to resolve it since I resolved it in my local environment and it appeared to still be affecting the current development branch.

**Comment by Molkobain** [comment]
No problem @alally , it's planned to be fixed in 3.0.1 anyway :)

Thanks again for pointing it out!
Guillaume

**Comment by Molkobain** [comment]
Fixed [here](https://github.com/Combodo/iTop/commit/f9e8bf88c89f75000685843a603c31a7dd1b1824)

**Pull request closed without merging**
