### PR TITLE
Cleanup documentation

### PR DESCRIPTION
**Pull request by Hipska**

### CODE REVIEW

**Review by bruno-ds — CHANGES_REQUESTED** [review]
The `/**` (with two *) on the first line is very important. Without it the comments is not parsed as a phpdoc DocBlock.

For the two other lines, I can't quite see your modifications for now as I'm on my phone.

**Comment by Molkobain** [comment]
Hello @Hipska ,

Is this a WIP PR? I don't see anything beside the `/**` becoming `/*`, which as Bruno said is not a good thing as it would break PHP documentation.

Guillaume

**Comment by Hipska** [comment]
No this PR fixes broken phpdoc

**Comment by Molkobain** [comment]
Oh so, it's the other way around, you added the '*', sorry! 😅

**Comment by Hipska** [comment]
Yeah, I think the colors and `+` and `-` signs already give a hint 😉😇

**Review by piRGoif — APPROVED** [review]

**Comment by piRGoif** [comment]
Nice catch, thanks !

**Pull request merged**
