### PR TITLE
Add attachment icon for movie files

### PR DESCRIPTION
**Pull request by Hipska**
We get more and more people that make a screencast and add this to their ticket.

Icon source: https://iconarchive.com/show/filetype-icons-by-filetypeicons/movie-icon.html

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello @Hipska ,

Good idea. As we started to changed file icons in the last release and in order to be more consistent with the upcoming iTop 2.8, could you rather choose a "flat" style icon? [Here ](https://www.flaticon.com/search?word=video%20file%20flat)is one of the resources you can check

**Comment by Hipska** [comment]
I don't see any flat style icon for these file icons. Feel free to add the respective file yourself. Normally it's possible to push to our branch as you are a iTop maintainer. (Although I don't see that checkbox anymore)

**Comment by Molkobain** [comment]
You can add [this one](https://www.flaticon.com/free-icon/video_1803961?term=video%20file%20flat&page=2&position=60), it's not perfect but closer to the future look and feel. Thanks.

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Merged, thanks!

**Pull request merged**
