### PR TITLE
:globe_with_meridians: RU UI translations for 3.0

### PR DESCRIPTION
**Pull request by vbkunin**

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello Vladimir,

Thank you for the translations! 🙏 Will check them soon.

Guillaume

**Comment by Molkobain** [comment]
Some entries of the edited files are not translated yet, should we wait for you to complete the translations before merging?

**Comment by ilya-stukalov** [comment]
> Some entries of the edited files are not translated yet, should we wait for you to complete the translations before merging?

Good day! We wanted to send translations before release and were afraid not to be in time, that's why we sent them not completed. We are planning to send additional PR on this Friday, so, if release is after Friday, please, do not merge yet.

**Comment by piRGoif** [comment]
Hello,
No worries we are currently working on a beta4, and we will have at least a beta5. 
So if you are willing to add some more modifications this coming weeks, just commit to this pr : that will ease our review process. If you want to take more than few days, then you could set your PR to draft, that will also be easier for us.
Thanks !

**Comment by Molkobain** [comment]
Yep, just let us know when the PR is ready 😊

**Comment by vbkunin** [comment]
Hello,
I'm going to add some translations soon, do I need to rebase the branch and recreate PR or something else to resolve the conflict?

**Comment by piRGoif** [comment]
Hello,
Yes please rebase the branch and resolve the conflict.
We never manage to rebase properly by editing the PR in GitHub, you might do this on your dev env then force push

**Comment by vbkunin** [comment]
Hello!
That's all we want to add to the PR at the moment.

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Checked out, reviewed, validated. Seems all good! A huge thank you Vladimir ✌

**Comment by Molkobain** [comment]
@ilya-stukalov could you send me your fullname and postal address to guillaume.lajarige combodo.com so we could send you some thank you stickers for your contribution?

Cheers,
Guillaume

**Comment by ilya-stukalov** [comment]
> @ilya-stukalov could you send me your fullname and postal address to guillaume.lajarige combodo.com so we could send you some thank you stickers for your contribution?
> 
> Cheers, Guillaume

Good day!
Thank you so much!
I sent you an email.

Best Regards,
Ilya Stukalov

**Pull request merged**
