### PR TITLE
Fix duplicate version loading

### PR DESCRIPTION
**Pull request by Hipska**
Only one is needed.

### CODE REVIEW

**Review by piRGoif — APPROVED** [review]

**Comment by piRGoif** [comment]
Thanks Hipska !
Both lines (L277 and L280) were pushed from the same commit (d0d9b1ce504a41613ce574eae13860fd05ee0954), really seems like a typo... I approve the change, but we will take a look with the rest of the team to be sure.

**Comment by Molkobain** [comment]
Looks good! I assume you didn't encounter any bug, just found it looking through the code?

**Review by Molkobain — APPROVED** [review]

**Comment by Hipska** [comment]
Correct! Not a bug, just stumbled across it.

**Comment by piRGoif** [comment]
2 approvers => merging !

**Pull request merged**
