### PR TITLE
zh-cn dict update

### PR DESCRIPTION
**Pull request by purplegrape**

### CODE REVIEW

**Comment by purplegrape** [comment]
due to wrong action , plz use the latest one commit, others can be ignored.

**Comment by purplegrape** [comment]
the dev branch seems update too frequently ,
should I update the support/3.0 branch directly?

**Comment by Hipska** [comment]
You don't need to update/merge with the dev branch if your changes in the PR are not conflicting..

Please fix your PR branch (by reverting maybe?), otherwise I don't think it will be accepted..

**Comment by piRGoif** [comment]
Hello,
First of all thanks for your contributions !

As stated in our [CONTRIBUTING.md](https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md#where-to-start-), always start with the develop branch, and don't forget to enable maintainers modifications !
Like Hipska said, a PR without conflicts can be merged with no problem.

**Pull request closed without merging**
