### PR TITLE
Add ES_CR translations to Application Upgrade Menu

### PR DESCRIPTION
**Pull request by lazki**

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello @lazki ,

Thank you for the translations, much appreciated! It's a bit late for them to be integrated in iTop 2.7.0 as we are already packaging everything but we will integrate them in the 2.7.1 that will probably come a few months later.

Have a nice day,
Guillaume

**Comment by piRGoif** [comment]
Hello, 
We are ready to accept commits for the next 2.7.1 now.
Can you rebase your modifications on our master branch ? You will need to pull from upstream first...

**Comment by piRGoif** [comment]
> Can you rebase your modifications on our master branch ?

My apologies we changed our branch model recently (see the CONTRIBUTING.md for details) : the master branch doesn't exist anymore.

Can you rebase on support/2.7 ?

**Review by Molkobain — APPROVED** [review]

**Comment by eespie** [comment]
integrated in support/2.7

**Pull request closed without merging**
