### PR TITLE
N°7345 Accept DateTime objects for DBObject::Set() calls on AttributeDateTime and children

### PR DESCRIPTION
**Pull request by piRGoif**

### CODE REVIEW

**Comment by Hipska** [comment]
https://github.com/Combodo/iTop/blob/4e53deec9d96093df87b233249a9c071ae458d40/.github/pull_request_template.md?plain=1#L3-L5

**Comment by piRGoif** [comment]
Thomas, we already explained multiple times : we are asking this for external contributors, as we need to review their work without them being here to explain.
Combodo contributors are present during the reviews.

**Comment by piRGoif** [comment]
On this PR, what more information would you need ?

**Comment by Hipska** [comment]
In that case the text in the template is not correct.

Take an example to @Molkobain who does perfectly fills in this template and makes his PRs easy to understand by the community.

**Comment by piRGoif** [comment]
Thomas I don't understand ?
My guess is that you have one of the following concerns :

- Not enough informations in that PR for it to be merged
=> You can of course share your opinion, but naturally Combodo dev team will be the one to decide what are the informations it needs.

- Unfair that an external contributor has to fill a lot of informations, whearas a repo maintainer doesn't
=> I can't help on that. I would just say that the more information an external contributor provide, the easier it will be for a Combodo dev team member to handle the PR through the different steps of the process.

- You don't have enough information to undestand the modification made in this PR
=> Even if there is only a one line title provided in this PR, I'm unsure what I could had to help ? Maybe error message before modification ? I'm open to suggestion.

**Comment by Hipska** [comment]
It's indeed point 2 and a bit of point 1:

> * Not enough informations in that PR for it to be merged
>   => You can of course share your opinion, but naturally Combodo dev team will be the one to decide what are the informations it needs.

Of course it's Combodo dev team to decide, and this was indeed me sharing my opinion. I don't think I stated something else.

> * Unfair that an external contributor has to fill a lot of informations, whearas a repo maintainer doesn't
>   => I can't help on that.

Yes you can, it is your PR. You deliberately removed the suggested description (from the template) and added nothing as description. As said, take an example from @Molkobain, this is much more friendly towards the community.

If the template really is not applicable for "internal" PRs, please have that mentioned in the template.

**Comment by piRGoif** [comment]
> You deliberately removed the suggested description

Yes I did.

When I create a PR my concerns are : 

* Comply with our coding standards (formatting, tests, ...)
* Comply with Combodo dev team internal process
* Having enough information for anyone to understand the modification and participate : what is the problem addressed and how it is solved

Do you have any other needs ?

> If the template really is not applicable for "internal" PRs, please have that mentioned in the template.

I don't understand what you are asking ? 
Reading your phrase literally, that would mean having an information so that when creating a PR Combodo dev team members know they can format their PR as they want. Combodo dev team don't need that obviously. So I guess you have other concerns ? 
What would you want to say there ? Aimed to which people ? 
Would you have any suggestion ?

**Comment by Hipska** [comment]
> Reading your phrase literally, that would mean having an information so that when creating a PR Combodo dev team members know they can format their PR as they want.

Yes, exactly this.

> Aimed to which people ?

Combodo dev, but also to the community officially stating that "Any PRs not following the guidelines or with missing information will not be considered." only counts for the community.

**Comment by piRGoif** [comment]
>> Reading your phrase literally, that would mean having an information so that when creating a PR Combodo dev team members know they can format their PR as they want.

>> Aimed to which people ?
> Combodo dev

Our team doesn't need this phrase to be added.

> but also to the community officially stating that "Any PRs not following the guidelines or with missing information will not be considered." only counts for the community.

Ok this is a clear request.
But we don't understand why you are asking this ? 

Can you explain why this phrase should be added to the community ?
For example in which situations having this phrase would be beneficial ? Or the other way around : not having this phrase would be a missing information for the community contributors ?

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Accepted during support PRs review

**Comment by piRGoif** [comment]
ImportTest::testImportFail_Date is failing on this branch :(
Having a look...

**Comment by piRGoif** [comment]
The failing test has the whole error message including exception class in a big expected string :(
Setting back this PR to support review so we can discuss on this !

**Comment by piRGoif** [comment]
PR #628 is also about ImportTest, and is already in the support review queue, so setting this one back for functional review.

**Comment by Molkobain** [comment]
Accepted during functional review.
@piRGoif will check with @v-dumas if this can affect and benefit to his newly "SetComputedDate()" change.

**Comment by piRGoif** [comment]
Discussed with Vincent, I modified the \DBObject::SetComputedDate method to remove the now unecessary conversion.
Didn't find any other of the corresponding methods (SetDateIfNull, SetComputedDateIfNull, ...) using a conversion.

**Pull request merged**
