### PR TITLE
:bug: Fix session start check

### PR DESCRIPTION
**Pull request by dlepenven**
:bug: Add a simple test on session start and trigger an exception when it fails

### CODE REVIEW

**Comment by piRGoif** [comment]
Thanks, 
Relates to https://sourceforge.net/p/itop/tickets/1829/

**Comment by dlepenven** [comment]
I made a mistake here, should be === false not !== false :-(

**Comment by dlepenven** [comment]
In my case, I use a memcached server to handle PHP sessions.

During "huge" requests, that can take severals seconds, if I open a new tab or any itop page, I have already a request handled by the server, so the session file is locked.
The memcached system make some retries until the number configured.
in this case session_start() returns a false.

So the idea is to handle this case with a simple test.

https://www.php.net/manual/fr/function.session-start.php :
Return Values ¶
This function returns TRUE if a session was successfully started, otherwise FALSE.

**Comment by piRGoif** [comment]
> During "huge" requests, that can take severals seconds

Indeed in iTop we do not do any session_write_close()... Do you have some examples of actions that could block your iTop ?

Having a chat about the solution you proposed with the rest of the R&D team, we think that there should always be an error thrown in such case, by the call to \LoginWebPage::DoLoginEx ? 
Do you have any use case were it's not ?

**Comment by dlepenven** [comment]
> > During "huge" requests, that can take severals seconds
> 
> Indeed in iTop we do not do any session_write_close()... Do you have some examples of actions that could block your iTop ?
> 
> Having a chat about the solution you proposed with the rest of the R&D team, we think that there should always be an error thrown in such case, by the call to \LoginWebPage::DoLoginEx ?
> Do you have any use case were it's not ?



> Indeed in iTop we do not do any session_write_close()... Do you have some examples of actions that could block your iTop ?
> 
> Having a chat about the solution you proposed with the rest of the R&D team, we think that there should always be an error thrown in such case, by the call to \LoginWebPage::DoLoginEx ?
> Do you have any use case were it's not ?

The real problem is not really the freeze. It is the fact that the session_start could fail, and not having any informations about this. The solution I propose seems to cover my problem, but maybe it should be extended to others functions I don't know. 
An other case of session fails for exemple is when I configure a memcache server in PHP but doesn't start it. In this case, I always return to the login page in iTop.

**Comment by piRGoif** [comment]
> The real problem is not really the freeze. It is the fact that the session_start could fail, and not having any informations about this.

We were thinking that because of the DoLoginEx() call, if session fails to load, being redirected to the login screen would give enough information ? And most importantly prevent the code from being executed...

**Comment by Hipska** [comment]
Would the better solution then be, that user still gets redirected to the login page and a message of failed `session_start` be put into the log file? This way the user don't get useless details and the admin can find the root cause.

**Comment by dlepenven** [comment]
> > The real problem is not really the freeze. It is the fact that the session_start could fail, and not having any informations about this.
> 
> We were thinking that because of the DoLoginEx() call, if session fails to load, being redirected to the login screen would give enough information ? And most importantly prevent the code from being executed...

Yes indeed! My solution is a little.... brutal...

> Would the better solution then be, that user still gets redirected to the login page and a message of failed `session_start` be put into the log file? This way the user don't get useless details and the admin can find the root cause.

 And if it is possible to show a message to the user it would be even better :D

**Comment by dlepenven** [comment]
I close my request since the edits I made are not okay for the moment.

**Comment by piRGoif** [comment]
Thanks @dlepenven !
I like the idea proposed by Hipska... That could be something to do in the future.

**Pull request closed without merging**
