### PR TITLE
Add ES CR translations for DB Tools

### PR DESCRIPTION
**Pull request by lazki**
I think this translations should be ported to release/2.7.0

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello @lazki ,

Same as for the other 2, we keep this for v2.7.1 !

Thanks,
Guillaume

**Comment by piRGoif** [comment]
Hello, 
We are ready to accept commits for the next 2.7.1 now.
Can you rebase your modifications on our master branch ? You will need to pull from upstream first...

**Comment by piRGoif** [comment]
> Can you rebase your modifications on our master branch ?

My apologies we changed our branch model recently (see the CONTRIBUTING.md for details) : the master branch doesn't exist anymore.

Can you rebase on support/2.7 ?

**Comment by eespie** [comment]
Integrated into support/2.7

**Pull request closed without merging**
