### PR TITLE
improved zh-cn dict for 3.0.x release

### PR DESCRIPTION
**Pull request by purplegrape**
backport chinese translations if you guys wana release a new 3.0.x in future

### CODE REVIEW

**Comment by Hipska** [comment]
3.0 is not a [LTS release](https://www.itophub.io/wiki/page?id=latest:release:start#calendar_view). As 2.7 is a LTS release, it might be better to have updated translations for that version instead.

**Comment by purplegrape** [comment]
> 3.0 is not a [LTS release](https://www.itophub.io/wiki/page?id=latest:release:start#calendar_view). As 2.7 is a LTS release, it might be better to have updated translations for that version instead.

thanks for your remind.

**Comment by piRGoif** [comment]
Hello,

Indeed we are close to the 3.1.0 packaging, and there shouldn't be new 3.0.* version after that. As mentioned in [our contribution guide](https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md), don't hesitate to ask before any proposition on the support branches.

I'll ask about integrating your contribution on next review.

**Review by piRGoif — APPROVED** [review]

**Comment by piRGoif** [comment]
Hello, 
The review decided to reject your contribution, for the reason I suspected : there should be no 3.0.* version anymore, all users of the 3.0 branch are encouraged to migrate to the 3.1 branch.
Many thanks anyway, and next time don't hesitate to ask

**Pull request closed without merging**
