### PR TITLE
N°7137 - DataSynchro: Remove "Organization" as default value for SynchroReplica->dest_class

### PR DESCRIPTION
**Pull request by Hipska**
It appears to be existing since commit f3f2eb5c797ec40d331798e134b3cd73b5bfd4ea and I never found this a logical value..
https://github.com/Combodo/iTop/blame/f3f2eb5c797ec40d331798e134b3cd73b5bfd4ea/synchro/synchrodatasource.class.inc.php#L1006

### CODE REVIEW

**Comment by piRGoif** [comment]
Hello,
The commit introducing the default value for SynchroReplica.dest_class is actually f3f2eb5c, made back in 2011 (!!)
There are no explicit reason invoked in the commit message nor bug reference that could help :/

**Comment by Hipska** [comment]
Hmm, right. But there are also a lot in between that don't have this as default value..

**Comment by piRGoif** [comment]
I don't see that. Which commit(s) are you refering to ?

**Comment by Hipska** [comment]
~~So 2dfad12553198362118f18ca7163b16e771f8ef5 was only 4 years ago and changed from not having a default value to having `Organization`. So the commits before that didn't have a default..~~

Nevermind, I just saw the commit before that did actually had this default as well, so you are right it is since f3f2eb5c797ec40d331798e134b3cd73b5bfd4ea, updated the PR description.

**Comment by Molkobain** [comment]
Accepted during technical, it makes no sense to have this value and null value is allowed anyway.

**Comment by Molkobain** [comment]
Accepted during functional review. To be retrofitted in support/2.7.

**Comment by Molkobain** [comment]
@Hipska can you modify the PR (and the branch if necessary) to target support/2.7?

**Comment by Hipska** [comment]
Done

**Comment by Molkobain** [comment]
Thanks, I'll just wait for 2.7.10 to be released and I'll merge.

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Did you test it @Hipska ?
It didn't even pass the setup.

**Comment by Hipska** [comment]
Oh, it should probably be `'default_value' => '',` then?

Don't know anymore why I removed that line.

**Comment by Molkobain** [comment]
I know the fix, but I'm surprised you didn't test your branch.

**Comment by Hipska** [comment]
No, I don't have any 2.7 systems running anymore..

**Comment by Molkobain** [comment]
Fixed in [7a0a4e3](https://github.com/Combodo/iTop/commit/7a0a4e377bdc859b0935b46ae5cba2796904048a)

**Pull request merged**
