### PR TITLE
N°5603 - Autocomplete fails with error for an external key pointing to an abstract class with no friendlyname

### PR DESCRIPTION
**Pull request by accognet**
Autocomplete fails with error for an external key pointing to an abstract class with no friendlyname.

### CODE REVIEW

**Comment by Molkobain** [comment]
I understand that the code was already mostly duplicated but as the code is growing could you factorize the whole switch/case in a dedicated method to ease maintenance? For example `PrepareFilterForLoadValues(DBSearch $oFilter, string $sOperation)`.

**Comment by Molkobain** [comment]
Moreover this will allow to add a unit test on this new method.

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Discussed with Anne-Catherine, code has been factorized a bit more and branch has been rebased onto support/3.0 to solve conflicts. Ready for technical review.

**Comment by rquetiez** [comment]
This change involves both a "one line fix" and a refactoring of duplicated code. Both are ok.
That said, the one line fix would be suitable for a fix on a minor release, whereas the refactoring makes it more risky : the diff is quite confusing and we do not have relevant unit test on that specific part.
Therefore, I do **not** recommend to merge that on branch 3.0. Rather, we'd better differ the change to **3.1**.

**Review by rquetiez — CHANGES_REQUESTED** [review]
Branch develop is more suitable for such a change

**Comment by Molkobain** [comment]
Discussed IRL, accepted during functional review. Go for 3.0.3 / 3.1.0

**Pull request merged**
