### PR TITLE
update chinese translation for 2.4 branch

### PR DESCRIPTION
**Pull request by purplegrape**
1、update chinese translation for 2.4 branch
2、fix some missing tab key just for goodlooking

### CODE REVIEW

**Comment by purplegrape** [comment]
I've already renamed the files ,thanks!

**Comment by piRGoif** [comment]
The PR has lost the original repo, did you delete it ? I can't get your code on my environment...
I'm merging your modifications but may come back to ask for some changes O:)

**Comment by purplegrape** [comment]
yes, I just delete the whole repo hours ago and fork a new one
I will fill it back asap

**Comment by piRGoif** [comment]
Everything is perfect, all of the english keys are present in the zh_cn files, many thanks !

Just for information, here are the missing zh_cn files in the support/2.4 branch :

* datamodels/2.x/itop-datacenter-mgmt/zh_cn.dict.itop-datacenter-mgmt.php
* datamodels/2.x/itop-endusers-devices/zh_cn.dict.itop-endusers-devices.php
* datamodels/2.x/itop-hub-connector/zh_cn.dict.itop-hub-connector.php
* datamodels/2.x/itop-sla-computation/zh_cn.dict.itop-sla-computation.php
* datamodels/2.x/itop-storage-mgmt/zh_cn.dict.itop-storage-mgmt.php
* datamodels/2.x/itop-virtualization-mgmt/zh_cn.dict.itop-virtualization-mgmt.php

Please note that this branch won't be merged to branches containing upper versions : this was created back when we were using SVN, so conflicts would be a nightmare to solve and also this won't be usefull to us.
As of today no 2.4.4 version release is planned.

About the repo referenced by this PR, no worry, just keep it next time : it's sometimes necessary for us to clone your code locally to use some extra tools (not everything can be done using a web browser and a pair of eyes ;) )

**Comment by purplegrape** [comment]
> 
> 
> Everything is perfect, all of the english keys are present in the zh_cn files, many thanks !
> 
> Just for information, here are the missing zh_cn files in the support/2.4 branch :
> 
>     * datamodels/2.x/itop-datacenter-mgmt/zh_cn.dict.itop-datacenter-mgmt.php
> 
>     * datamodels/2.x/itop-endusers-devices/zh_cn.dict.itop-endusers-devices.php
> 
>     * datamodels/2.x/itop-hub-connector/zh_cn.dict.itop-hub-connector.php
> 
>     * datamodels/2.x/itop-sla-computation/zh_cn.dict.itop-sla-computation.php
> 
>     * datamodels/2.x/itop-storage-mgmt/zh_cn.dict.itop-storage-mgmt.php
> 
>     * datamodels/2.x/itop-virtualization-mgmt/zh_cn.dict.itop-virtualization-mgmt.php
> 
> 
> Please note that this branch won't be merged to branches containing upper versions : this was created back when we were using SVN, so conflicts would be a nightmare to solve and also this won't be usefull to us.
> As of today no 2.4.4 version release is planned.
> 
> About the repo referenced by this PR, no worry, just keep it next time : it's sometimes necessary for us to clone your code locally to use some extra tools (not everything can be done using a web browser and a pair of eyes ;) )

zh_cn.dict.itop-hub-connector.php  has not translated yet, it's added after itop 2.4.0 
others you said are almost empty. 
anyway, I will check them later via smaller PR , thanks

**Comment by piRGoif** [comment]
The Hub connector was added in iTop 2.4.1, so it's present in the 2.4 branch : see https://github.com/Combodo/iTop/tree/support/2.4/datamodels/2.x/itop-hub-connector

**Pull request merged**
