### PR TITLE
Make it possible to add return path for mails

### PR DESCRIPTION
**Pull request by larhip**
This would give the possibility to create child classes of `ActionEmail` and add a return path

### CODE REVIEW

**Review by Hipska — DISMISSED** [review]

**Comment by Molkobain** [comment]
Hello Lars,

Could you give some details on what `return-path` is and what it would bring functionaly?

Thanks

**Comment by bastischubert** [comment]
With the return path you can specify where NON-Deliverys (aka Bounce) mails will be sent to. This is useful as itop tends to create mail-loops (sometimes)

**Comment by Molkobain** [comment]
Thanks for the info @bastischubert !

**Comment by piRGoif** [comment]
Hello @larhip , why did you closed your PR ?

**Comment by larhip** [comment]
HI @piRGoif 
sorry for that. This was not goal.
I reset our develop branch in itomig-de to get it up-to-date with your develop branch and I forgot about this PR which was based on our develop branch.
I moved this commit regarding the return path of the mail in a another branch (https://github.com/itomig-de/iTop/tree/feature/email-returnpath) are you able to make this PR based on the other branch or should we let this PR closed and I will open a second one?
Really sorry about this :see_no_evil:

**Comment by piRGoif** [comment]
Oh ok I see :)
Seems I can't nor reopen nor change branch of this PR... But I would be glad to keep it... 
Can't you change it (reopen then change source branch) on your side ? Or you could also give Combodo dev access ("allow edits from maintainers" option, see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by larhip** [comment]
Hi Pierre,
I will try to do so. But I am just able to reopen it in case of a new commit in the develop branch. So i just merged the feature-branch into develop. I will try to change to source branch after the reopen.

**Comment by larhip** [comment]
Unfortunately I am just able to change the target branch to the dource:
grafik
You should be also able to edit this PR
grafik
Anyhow. Now this PR is open again and you are able to see the changed files.
Unfortunately in two commit (the original and one for the merge)

**Comment by piRGoif** [comment]
This was submitted in Combodo ticket DB as N°2765, candidate for iTop 2.8.

@larhip sorry it took us so much time to accept this PR... We were (and still are in a way) quite busy with the 2.7.0... We are aiming to integrate this in 2.8.0.

**Review by piRGoif — APPROVED** [review]

**Comment by piRGoif** [comment]
This was also merged to support/2.7 branch, and will be available in the future 2.7.1 version.

**Pull request merged**
