### PR TITLE
improved chinese for 2.7

### PR DESCRIPTION
**Pull request by purplegrape**
improved chinese translation,
hope it's helpful, thanks in advance

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello @purplegrape 

Thanks for the translations! I'll check with the product team if we still accept translations on the 2.7.x or if they will be for the upcoming 3.0.0. Either way you are gonna need to change your base branch, but I'll tell which and how in few days.

Cheers,
Guillaume

**Comment by Molkobain** [comment]
Hello @purplegrape ,

Just discussed with the Product team, they are ok for the translations to be in an upcoming 2.7.x; depending on when you will make the following adjustment, it will be 2.7.5 or 2.7.6.

Can you please rebase your branch to the `support/2.7` instead of the `support/2.7.4`? Same for the target branch in our repository, it should also be `support/2.7`

Thanks,
Guillaume

**Comment by piRGoif** [comment]
@purplegrape we could rebase ourselves, did you checked the ["Allow edits from maintainers" PR checkbox](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) ?

**Comment by purplegrape** [comment]
will push to support/2.7

**Pull request closed without merging**
