### PR TITLE
Russian translations

### PR DESCRIPTION
**Pull request by vbkunin**
Hi! Here are the latest Russian translations.

### CODE REVIEW

**Comment by Molkobain** [comment]
Hi @vbkunin ,

Thanks for the update on the translations!
Could you change the target branch to release/2.6 so it's part of the 2.6.0? (Don't know if the PR can be edited or if you need tout make a new one)

**Comment by Hipska** [comment]
This makes me wonder what will happen with the 2.6 branch after release? Merged again with develop? If not, PR to develop branch is better. Yup can do cherry pick after this PR.

**Comment by piRGoif** [comment]
Hello,

@Hipska  : We're following the GitFlow branch model (https://nvie.com/posts/a-successful-git-branching-model/).
As we're working on the 2.6 release (beta was out on october 26th), we created a dedicated release branch so that we could still submit to the develop branch for the next 2.7 version. 
When 2.6 will be ready, release/2.6 branch will be merge to both master and develop branches (finish release gitflow command). At that time master will contain the previous version (2.6), and develop the version in development (2.7).

@vbkunin : sorry we're getting 13 commits in this PR, 12 from develop, and yours (b724431) at the end. Can you rebase so that your commit only is on top of the release/2.6 branch ?

**Comment by vbkunin** [comment]
@piRGoif I've created a new RP with rebased branch: https://github.com/Combodo/iTop/pull/16.

**Comment by piRGoif** [comment]
Many thanks @vbkunin, reviewing #16 right now !

**Pull request closed without merging**
