### PR TITLE
N°4934 Improve German translation

### PR DESCRIPTION
**Pull request by ChristianBeer**
Replaces #276

### CODE REVIEW

**Review by piRGoif — APPROVED** [review]
Verified manually and with \Combodo\iTop\Test\UnitTest\Integration\DictionariesConsistencyTest::testStandardDictionariesPhpSyntax, everything OK for me !

**Comment by piRGoif** [comment]
@ChristianBeer does your PR is ready to merge ? 
I'll check with our product team, but as window is closing for iTop 3.0.1, this might be merged for 3.0.2 instead

**Comment by ChristianBeer** [comment]
Yes, the PR is ready to be merged. It would be great if this could be included in 3.0.1 as I want to start using iTop for my department sometime in April. But it's just a whish, no pressure.

**Comment by piRGoif** [comment]
Ok thanks :)
Waiting for our Product team answer to see if this will be merged for 3.0.1

**Comment by piRGoif** [comment]
Product team is ok to merge for 3.0.1 !

**Comment by ChristianBeer** [comment]
Thanks for including this in 3.0.1. Very much appreciated.

**Comment by Molkobain** [comment]
Can you send me your full name and postal address to guillaume.lajarige / combodo.com, we would like to send you [thankful stickers](https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md#-we-are-thankful) for contributing :)

Cheers
Guillaume

**Pull request merged**
