### PR TITLE
N°7693 - Update polish translations

### PR DESCRIPTION
**Pull request by DudekArtur**
## Base information
Translations

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have tested all changes I made on an iTop instance
- [ ] I have added a unit test, otherwise I have explained why I couldn't
- [ ] Is the PR clear and detailed enough so anyone can understand digging in the code?

### CODE REVIEW

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Thanks for the huge amount of translations! Is your PR ready to merge or shall we wait a bit?

**Comment by Molkobain** [comment]
@DudekArtur could you send me your postal address and fullname to guillaume.lajarige at combodo.com so we can send you thankful stickers ? :)

**Comment by DudekArtur** [comment]
> Thanks for the huge amount of translations! Is your PR ready to merge or shall we wait a bit?

Yes. It is ready to connect. I hope everything is OK.

**Review by Molkobain — APPROVED** [review]

**Comment by DudekArtur** [comment]
> @DudekArtur could you send me your postal address and fullname to guillaume.lajarige at combodo.com so we can send you thankful stickers ? :)

There is no need. I'm translating iTop for my own use and by sharing it I hope someone else will benefit. Kind regards.

**Comment by Molkobain** [comment]
This was just merged under https://github.com/Combodo/iTop/commit/33b6f2cbc487191766c632f6352227fe2bb138f6
Thanks a lot @DudekArtur for your contributions!

_The PR was based on the `develop` branch instead of the `support/3.2`. In order to make your translations available for iTop 3.2 instead of iTop 3.3, I retrieved your branch locally and rebased myself._

_The translations appear in your name in the git history, but this PR could not be merged as is._

_For future PRs it is recommended that you make a new branch for each PR, so that we can apply modifications on it and merge the PR correctly. In the present case, as the PR was made on your `develop` branch, I could not do anything on it or I would have broke your iTop fork._

**Pull request closed without merging**
