### PR TITLE
make demo_mode effect more expressive

### PR DESCRIPTION
**Pull request by bruno-ds**
Since an empty json could be a bug, 
Make demo_mode effect expressive.

### CODE REVIEW

**Comment by Molkobain** [comment]
Why don't we send anything when the instance is in demo mode? It could be someone using the iTop as a showcase but still getting extensions from the Hub from time to time. So I think we could use having the instance information on our side.

**Comment by bruno-ds** [comment]
with @dflaven we tough it could possibly lead to security issue, so we preferred to not divulgate anything.

**Review by rquetiez — APPROVED** [review]

**Comment by piRGoif** [comment]
The team did validate this in PR review this afternoon !

@bruno-ds, a last though, shouldn't this be merged to master or support/2.5 ? If you agree, can you do a rebase of your branch ? (there's a mean to rebase a PR in GitHub but it seems to give very strange results...)

**Comment by piRGoif** [comment]
Was cherry picked because rebase wasn't working :/ => closing this PR !

**Pull request closed without merging**
