### PR TITLE
🐛  Fixing error during setup

### PR DESCRIPTION
**Pull request by DarkNight97boss**
installing version 3.2.0 dev During the first installation I encountered problems preventing the installation, the file to correct is the following: datamodels/2.x/authent-cas/src/CASLogger.php.

This is an example error that was shown to me in the log.

Declaration of Combodo\iTop\Cas\CASLogger::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void

However, this error affects all methods from Emergency to log included.

### CODE REVIEW

**Comment by DarkNight97boss** [comment]
I also report that by installing the custom extension to customize the portal interface, multiple errors are generated by the chrome console

GET http://173.249.59.208/itopdev/env-production/itop-portal-base/portal/public/js/portal_leave_handler.js?t=1703497082.9735 net::ERR_ABORTED 404 (Not Found)
jquery-migrate.dev.js?t=1703497082.9735:71 JQMIGRATE: Migrate is installed with logging active, version 3.1.0
jquery-migrate.dev.js?t=1703497082.9735:99 JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate.dev.js?t=1703497082.9735:99
get @ jquery-migrate.dev.js?t=1703497082.9735:112
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
jquery-migrate.dev.js?t=1703497082.9735:101 console.trace
migrateWarn @ jquery-migrate.dev.js?t=1703497082.9735:101
get @ jquery-migrate.dev.js?t=1703497082.9735:112
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
jquery-migrate.dev.js?t=1703497082.9735:99 JQMIGRATE: jQuery.expr.filters is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate.dev.js?t=1703497082.9735:99
get @ jquery-migrate.dev.js?t=1703497082.9735:112
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:13
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:13
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
jquery-migrate.dev.js?t=1703497082.9735:101 console.trace
migrateWarn @ jquery-migrate.dev.js?t=1703497082.9735:101
get @ jquery-migrate.dev.js?t=1703497082.9735:112
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:13
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:13
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
jquery.min.js?t=1703497082.9735:2 jQuery.Deferred exception: oBodyElem.portal_leave_handler is not a function TypeError: oBodyElem.portal_leave_handler is not a function
    at HTMLDocument.<anonymous> (http://173.249.59.208/itopdev/pages/exec.php/?exec_module=itop-portal-base&exec_page=index.php&portal_id=itop-portal:441:27)
    at e (http://173.249.59.208/itopdev/js/jquery.min.js?t=1703497082.9735:2:30005)
    at t (http://173.249.59.208/itopdev/js/jquery.min.js?t=1703497082.9735:2:30307) undefined
S.Deferred.exceptionHook @ jquery.min.js?t=1703497082.9735:2
t @ jquery.min.js?t=1703497082.9735:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
fire @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
ready @ jquery.min.js?t=1703497082.9735:2
B @ jquery.min.js?t=1703497082.9735:2
jquery.min.js?t=1703497082.9735:2 Uncaught TypeError: oBodyElem.portal_leave_handler is not a function
    at HTMLDocument.<anonymous> (exec.php/?exec_module=itop-portal-base&exec_page=index.php&portal_id=itop-portal:441:27)
    at e (jquery.min.js?t=1703497082.9735:2:30005)
    at t (jquery.min.js?t=1703497082.9735:2:30307)
(anonymous) @ exec.php/?exec_module=itop-portal-base&exec_page=index.php&portal_id=itop-portal:441
e @ jquery.min.js?t=1703497082.9735:2
t @ jquery.min.js?t=1703497082.9735:2
setTimeout (async)
S.readyException @ jquery.min.js?t=1703497082.9735:2
(anonymous) @ jquery.min.js?t=1703497082.9735:2
e @ jquery.min.js?t=1703497082.9735:2
t @ jquery.min.js?t=1703497082.9735:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
fire @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
t @ jquery.min.js?t=1703497082.9735:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
fire @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
ready @ jquery.min.js?t=1703497082.9735:2
B @ jquery.min.js?t=1703497082.9735:2

@Molkobain

**Comment by DarkNight97boss** [comment]
I also report that by installing the custom extension to customize the portal interface, multiple errors are generated by the chrome console

```
GET http://localhost/itopdev/env-production/itop-portal-base/portal/public/js/portal_leave_handler.js?t=1703497082.9735 net::ERR_ABORTED 404 (Not Found)
jquery-migrate.dev.js?t=1703497082.9735:71 JQMIGRATE: Migrate is installed with logging active, version 3.1.0
jquery-migrate.dev.js?t=1703497082.9735:99 JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate.dev.js?t=1703497082.9735:99
get @ jquery-migrate.dev.js?t=1703497082.9735:112
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
jquery-migrate.dev.js?t=1703497082.9735:101 console.trace
migrateWarn @ jquery-migrate.dev.js?t=1703497082.9735:101
get @ jquery-migrate.dev.js?t=1703497082.9735:112
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
jquery-migrate.dev.js?t=1703497082.9735:99 JQMIGRATE: jQuery.expr.filters is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate.dev.js?t=1703497082.9735:99
get @ jquery-migrate.dev.js?t=1703497082.9735:112
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:13
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:13
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
jquery-migrate.dev.js?t=1703497082.9735:101 console.trace
migrateWarn @ jquery-migrate.dev.js?t=1703497082.9735:101
get @ jquery-migrate.dev.js?t=1703497082.9735:112
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:13
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:13
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
(anonymous) @ jquery-ui.custom.min.js?t=1703497082.9735:6
jquery.min.js?t=1703497082.9735:2 jQuery.Deferred exception: oBodyElem.portal_leave_handler is not a function TypeError: oBodyElem.portal_leave_handler is not a function
    at HTMLDocument.<anonymous> (http://localhost/itopdev/pages/exec.php/?exec_module=itop-portal-base&exec_page=index.php&portal_id=itop-portal:441:27)
    at e (http://localhost/itopdev/js/jquery.min.js?t=1703497082.9735:2:30005)
    at t (http://localhost/itopdev/js/jquery.min.js?t=1703497082.9735:2:30307) undefined
S.Deferred.exceptionHook @ jquery.min.js?t=1703497082.9735:2
t @ jquery.min.js?t=1703497082.9735:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
fire @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
ready @ jquery.min.js?t=1703497082.9735:2
B @ jquery.min.js?t=1703497082.9735:2
jquery.min.js?t=1703497082.9735:2 Uncaught TypeError: oBodyElem.portal_leave_handler is not a function
    at HTMLDocument.<anonymous> (exec.php/?exec_module=itop-portal-base&exec_page=index.php&portal_id=itop-portal:441:27)
    at e (jquery.min.js?t=1703497082.9735:2:30005)
    at t (jquery.min.js?t=1703497082.9735:2:30307)
(anonymous) @ exec.php/?exec_module=itop-portal-base&exec_page=index.php&portal_id=itop-portal:441
e @ jquery.min.js?t=1703497082.9735:2
t @ jquery.min.js?t=1703497082.9735:2
setTimeout (async)
S.readyException @ jquery.min.js?t=1703497082.9735:2
(anonymous) @ jquery.min.js?t=1703497082.9735:2
e @ jquery.min.js?t=1703497082.9735:2
t @ jquery.min.js?t=1703497082.9735:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
fire @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
t @ jquery.min.js?t=1703497082.9735:2
setTimeout (async)
(anonymous) @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
fire @ jquery.min.js?t=1703497082.9735:2
c @ jquery.min.js?t=1703497082.9735:2
fireWith @ jquery.min.js?t=1703497082.9735:2
ready @ jquery.min.js?t=1703497082.9735:2
B @ jquery.min.js?t=1703497082.9735:2
```

@Molkobain

**Comment by Molkobain** [comment]
Hello @DarkNight97boss could you tell us which version of PHP you are running when you encounter these errors during the setup?

**Comment by DarkNight97boss** [comment]
> Hello @DarkNight97boss could you tell us which version of PHP you are running when you encounter these errors during the setup?

PHP 8.2

**Comment by piRGoif** [comment]
iTop 3.1.* versions aren't yet compatible with PHP 8.2 unfortunately. 
At least iTop 3.2.0 should be (Combodo reference : N°6037)

We will however review your contribution (next review should happen next month)

**Comment by Molkobain** [comment]
Hello @DarkNight97boss ,

This has been fixed during iTop 3.2 libraries upgrade, see [6342e0](https://github.com/Combodo/iTop/commit/6342e0065a986755e259a240b64de42013ba58a6).
Italian translations will be merged with your other PR.

Thanks for the report!
Guillaume

**Comment by piRGoif** [comment]
Hello @DarkNight97boss, can you confirm what iTop you were using ? This bug should only have been present during a very small amount of time on a feature branch, and never delivered to a package ?

**Comment by DarkNight97boss** [comment]
Hello @piRGoif i'm currently using 3.2.0-dev on my dev env.

3.1.1.1 maybe have important issue, please take a look: https://sourceforge.net/p/itop/tickets/2228/

**Comment by piRGoif** [comment]
What you are calling "3.2.0-dev" is a direct git clone right ? Which branch and commit ?

**Comment by piRGoif** [comment]
(and yes saw your SF ticket, we will take a look)

**Comment by DarkNight97boss** [comment]
> What you are calling "3.2.0-dev" is a direct git clone right ? Which branch and commit ?

Yes, it is a git clone of dev, now my instance should need to pull (maybe) ty for checking

**Pull request closed without merging**
