### PR TITLE
:globe_with_meridians: N°5390 - Update german translations for OAuth client module

### PR DESCRIPTION
**Pull request by larhip**

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello Lars,

Thank you for the PR! Much appreciated ✌
I'll check with the product on which branch we would like this, might be 2.7.8 / 3.0.2 / 3.1.0.

Cheers,
Guillaume

**Comment by jbostoen** [comment]
On a related note, the class name's English translation is inconsistent with other occurrences where O**A**uth is used.

`'Class:OAuthClient' => 'Oauth Client',`

**Comment by Molkobain** [comment]
Hello Lars,

This will be included in iTop 2.7.8 / 3.0.2 / 3.1.0, could you rebase your PR on the support/2.7 branch?

Thanks,
Guillaume

**Comment by Molkobain** [comment]
> On a related note, the class name's English translation is inconsistent with other occurrences where O**A**uth is used.

For languages other than german, done in [5829e69](https://github.com/Combodo/iTop/commit/5829e698da297002ecb6042545290b167fb11338)

**Comment by larhip** [comment]
This one got a little bit lost on my todo list, sorry for the delay!

This should be done now

**Comment by Molkobain** [comment]
Thanks!

**Review by Molkobain — APPROVED** [review]

**Pull request merged**
