### PR TITLE
N°4703 - Add "chat" / "in person" as possible "origin" value for tickets

### PR DESCRIPTION
**Pull request by Molkobain**
## Objective

Follow-up of SourceForge [ticket #2019](https://sourceforge.net/p/itop/tickets/2019/), adding the "chat" and "in_person" origin to `Ticket`/`UserRequest`/`Incident` classes to best reflect reality of modern helpdesk.

## TODOs once PR is merged

  * [ ] Add migration audit check

### CODE REVIEW

**Comment by jbostoen** [comment]
"in person" is one I've added long time ago ( https://github.com/jbostoen/iTop-custom-extensions/blob/e533b458b4b25ce2a03dd99780ab85bcccc587cd/web/extensions/jb-tweaks-request-mgmt-itil/datamodel.jb-tweaks-request-mgmt-itil.xml#L49 )

Perhaps also consider adding "monitoring"? It's perhaps a bit vague, but so is chat.

The basic idea is that sometimes you have alerts generated by other monitoring systems or scripts.

**Comment by Molkobain** [comment]
Thanks for the idea, this value was not in the ticket description, I'll propose it to the product team to see what they think of it.

**Review by steffunky — APPROVED** [review]

**Comment by Hipska** [comment]
@jbostoen "Monitoring" is already an existing option on Incidents (or simple request).

**Review by Hipska — APPROVED** [review]

**Review by Hipska — APPROVED** [review]

**Comment by Hipska** [comment]
Maybe also increment version number of the respective modules.

**Comment by Molkobain** [comment]
> Maybe also increment version number of the respective modules.

Datamodel and module.xxx.php files are already marked 3.1. are you referring to something else?

**Comment by Hipska** [comment]
Ouch. No, nevermind in that case.

**Pull request merged**
