### PR TITLE
🐛 Decimal values with aggregate functions (dashlet group by)

### PR DESCRIPTION
**Pull request by jbostoen**
#204 but rebased on develop branch

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello Jeffrey, thanks for the new PR! Would you mind adding some before / after screenshots for all concerned chart types (table, pie, bars)? (You can paste a screenshot directly into the GitHub editor without hosting the image somewhere first)

Guillaume

**Comment by jbostoen** [comment]
Sorry, haven't had the time yet to make the screenshots.

Update: seems like the dashlets are being worked on by Combodo?
They're not functional, even if I update the code to the current state of "develop" branch.
Even without the modifications I made, I can't configure a dashlet to show "average"

**Comment by jbostoen** [comment]
Before
20210618_before

After
20210618_after

**Comment by Molkobain** [comment]
Thanks Jeffrey! I'll present it to the product team and will get back to you.

Guillaume

**Comment by Molkobain** [comment]
This has been accepted and is going to be in the 3.0!
Internal ref number is N°4105

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Thanks Jeffrey! ✌

**Pull request merged**
