### PR TITLE
Updated Demo Organization parent/child relation

### PR DESCRIPTION
**Pull request by Hipska**
This updates the demo data so that "IT Department" is now a child of "Demo" organization

### CODE REVIEW

**Comment by Molkobain** [comment]
Hi @Hipska ,

What do you have in mind with this? *IT Dept* is not necessarely part of the *Demo* organization.

**Comment by Hipska** [comment]
As I have seen in most of Combodo demo's it is and it is also easier to explain new customers/users if that structure is already reflected in default example data.

**Comment by Molkobain** [comment]
As this is rather a _product owner_ decision, I'll forward it to @v-dumas .

**Comment by v-dumas** [comment]
We could do it, but should we lose time on such insignificant change? I don't think so.

**Comment by Hipska** [comment]
Well, I did it already for you, so you don't have to loose time 😉

**Comment by v-dumas** [comment]
All our tests rely on the demo data, changing them may break them, just thinking and checking if it does or not is a lost of time

**Comment by Hipska** [comment]
Okay, could you point me to that specific test that verifies the organization parent? Then I will update that one as well.. 👍

**Comment by zipkid** [comment]
> All our tests rely on the demo data, changing them may break them, just thinking and checking if it does or not is a lost of time

This kind of reaction makes me doubt if iTop is a product to adopt.... :-(

**Comment by Molkobain** [comment]
Hi guys,

What Vincent meant is that sample data are not subject to PRs yet, especially as they are part of our functional tests (part automated through Behat, part manual).

As a friendly reminder, for now we only consider PRs on *bug fixes* and *translations* (you can take a look at the [contributing guide](https://github.com/Combodo/iTop/blob/develop/CONTRIBUTING.md) for more detailled information).

Regarding this particular demand, the hierarchy was not intended but maybe we send mixed signals. That being said, you can easily bring your own samples through an extension if necessary 😊

**Pull request closed without merging**
