### PR TITLE
:globe_with_meridians: Config Menu title should be uppercase

### PR DESCRIPTION
**Pull request by lazki**
Changed "configuración" to "Configuración". 

I think this should be ported to release/2.7.0

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello @lazki ,

Thank for the translation, as I said in the other PR, we are keeping this for 2.7.1 as the 2.7.0 is already being packaged. 😊

Cheers,
Guillaume

**Comment by piRGoif** [comment]
Hello, 
We are ready to accept commits for the next 2.7.1 now.
Can you rebase your modifications on our master branch ? You will need to pull from upstream first...

**Comment by piRGoif** [comment]
> Can you rebase your modifications on our master branch ?

My apologies we changed our branch model recently (see the CONTRIBUTING.md for details) : the master branch doesn't exist anymore.

Can you rebase on support/2.7 ?

**Comment by piRGoif** [comment]
> Can you rebase your modifications on our master branch ?

My apologies we changed our branch model recently (see the CONTRIBUTING.md for details) : the master branch doesn't exist anymore.

Can you rebase on support/2.7 ?

**Comment by eespie** [comment]
integrated into Support/2.7

**Pull request closed without merging**
