### PR TITLE
🌐 N°6598 improved chinese translation

### PR DESCRIPTION
**Pull request by purplegrape**
🌐 improved chinese translation

### CODE REVIEW

**Comment by purplegrape** [comment]
trying to resove conflicts，hold on plz

**Comment by purplegrape** [comment]
the last conflict seems need to be resoved by hand
could you plz have a double check ?
@piRGoif

**Comment by piRGoif** [comment]
Hello @purplegrape , did you checked the "[allow edits by maintainers](https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)" PR option so I can try to solve the conflict myself ?

**Comment by purplegrape** [comment]
> Hello @purplegrape , did you checked the "[allow edits by maintainers](https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)" PR option so I can try to solve the conflict myself ?

i'm quite sure that the option [allow edits by maintainers] is enabled
if u have a issue ，maybe due to github outage
https://www.githubstatus.com/history

**Comment by piRGoif** [comment]
Hello,
Ok I'll have a look, but unfortunately we cannot integrate your work in 3.1.0, it will be at best in 3.1.1.
Will keep you posted !

**Comment by piRGoif** [comment]
During the last functional review it was said it is ok to rebase on the 3.1 branch. I will try to do that.

**Comment by piRGoif** [comment]
Merged manually ! Will be part of 3.1.1 version

**Pull request closed without merging**
