### PR TITLE
German translations Release/2.6

### PR DESCRIPTION
**Pull request by larhip**
Hi Combodo!
Just added all missing German translations regarding release 2.6.
Could please you merge them into your release 2.6 branch?
Thanks && Best regards,
Lars from ITOMIG

### CODE REVIEW

**Comment by Molkobain** [comment]
Hi @larhip ,

Thanks for the pull request! I see that you updated everything up to the 2.6.
Could you just squash all commits into one as this will be cleaner in the repo history? Otherwise, everything is good to merge.

Thanks,
Guillaume

**Comment by larhip** [comment]
Hi @Molkobain ,
just did it. So now is everything in just one commit and you could move forward and merge it into your repo.
Cheers
Lars

**Comment by Molkobain** [comment]
All done, thank you @larhip ! 🎉

**Comment by piRGoif** [comment]
Hello,
We are terribly sorry, we missed 3 strings in the dictionnary files for the new TagSet v2.6 feature. I've just add them in commit 4072ed09acade8231c53006db8091be71144d633.
@larhip, would you mind translate those strings with a new PR ?
Sorry again, and many thanks.

**Pull request merged**
