### PR TITLE
N°6417 - Update chinese translations thanks to @purplegrape

### PR DESCRIPTION
**Pull request by purplegrape**
1.check against via en.dict line by line ,fix quite a lot of missing lines;
2. tiny improvements for translation ;
3. partial zh_cn translations fallback just as en.dict if content changed heavily in few certain blocks.

### CODE REVIEW

**Comment by Molkobain** [comment]
Hello @purplegrape 

Thanks for the PR!
You changed a lot of chinese entries into english entries, was that done on purpose? Could you maybe translate them in chinese if they have evolve?

Guillaume

**Comment by purplegrape** [comment]
> Hello @purplegrape
> 
> Thanks for the PR! You changed a lot of chinese entries into english entries, was that done on purpose? Could you maybe translate them in chinese if they have evolve?
> 
> Guillaume

1. consistency come first，translation will be later (by me or others )
2. for entries of some special modules such as db tools, triggers, data source synchronization, I'm indeed considering to fallback to english style, since chinese translation will not be helpful for itop configuration or integration via other application. ( NOT in this PR )
3. plz merge if it has no php syntax error

**Comment by Hipska** [comment]
Untranslated entries (so ones that are still to be translated) should end with `~~`. See many other examples in other languages..

**Comment by purplegrape** [comment]
> Untranslated entries (so ones that are still to be translated) should end with `~~`. See many other examples in other languages..

OK. hold on this PR, will do it ASAP

**Comment by purplegrape** [comment]
this is another wave translations for my last weekend.
keep fallback or untranslated entries end via ~~

**Review by Molkobain — APPROVED** [review]
Great thanks, this a lot a lot better 🙌

**Review by Molkobain — APPROVED** [review]

**Comment by piRGoif** [comment]
Technical review : OK !

**Pull request merged**
