### PR TITLE
Change metamodel.class.php for toolkit iTop update

### PR DESCRIPTION
**Pull request by thiagoarcanjo**
To correct string comparison errors when performing itop update through the toolkit, change the file lines as below:

**FILE:** core/metamodel.class.php
**LINE:** 5471 to 5477, change to:

```
$bToBeChanged = false;
 $sActualFieldSpec = CMDBSource::GetFieldSpec($sTable, $sField);
 $sActualFieldSpec_correct = explode(" ",$sActualFieldSpec);
 $sDBFieldSpec_correct = explode(" ",$sDBFieldSpec);
 if (strcasecmp($sDBFieldSpec, $sActualFieldSpec) != 0)
 {
           if(is_array($sActualFieldSpec_correct) && (strcasecmp($sDBFieldSpec_correct[0], $sActualFieldSpec_correct[0]) == 0)) continue;
           else
           {
                      $bToBeChanged = true;
                      $aErrors[$sClass][$sAttCode][] = "field '$sField' in table '$sTable' has a wrong type: found '$sActualFieldSpec' while expecting '$sDBFieldSpec'";
           }
 }
```
This will add a second comparison, if the first one gives error, checking fields typing, disregarding charsets and default values.

### CODE REVIEW

**Comment by Hipska** [comment]
I think you are merging the wrong branches, please fix this.

**Comment by piRGoif** [comment]
Hello @thiagoarcanjo, many thanks for this PR following [our discussion on Sourceforge](https://sourceforge.net/p/itop/discussion/922361/thread/fd79e90461/?limit=25#baef/5bd1) :)
As Hipska pointed out you base your branch on master, you should rebase on develop please !

**Comment by thiagoarcanjo** [comment]
> Hello @thiagoarcanjo, many thanks for this PR following [our discussion on Sourceforge](https://sourceforge.net/p/itop/discussion/922361/thread/fd79e90461/?limit=25#baef/5bd1) :)
> As Hipska pointed out you base your branch on master, you should rebase on develop please !

Yep, I was confused about that, but now its fixed.

**Comment by bruno-ds** [comment]
Thanks for your PR :tada: !
But there are still several Conflicting files :(

**Comment by Hipska** [comment]
You need to fork this repository, do the changes and then select those as base for this merge request.

**Comment by piRGoif** [comment]
Hello,
I've just pushed our implementation of the fix. 
I'll be glad if you can test it !
I'm closing this PR, please continue discussion in the [corresponding sourceforge ticket](https://sourceforge.net/p/itop/tickets/1756/)

**Pull request closed without merging**
