### PR TITLE
Update install.txt

### PR DESCRIPTION
**Pull request by lazki**
Change old URL for new, linking to iTop Hub.

### CODE REVIEW

**Comment by Hipska** [comment]
Good catch, although the old URL still works and gives you a redirect to the new one.

**Review by Hipska — APPROVED** [review]

**Comment by lazki** [comment]
The old URL still works, but... openitop.org will be phased out in the future, isn't it?

**Comment by Molkobain** [comment]
Good catch indeed! Thanks Federico. ✌

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
> The old URL still works, but... openitop.org will be phased out in the future, isn't it?

Yep, we don't know when exactly, but the sooner we fix the URL the better, that way we minimize the number of packages with an outdated URL out there.

**Comment by Hipska** [comment]
@Molkobain be noted there are still a lot of links to openitop.org in readme.txt (Why is that file still there, since it has been replaced by README.md?)

**Comment by Molkobain** [comment]
@Hipska indeed yes those would need to be fixed as well! (if nobody makes a PR, I'll change them later).

Regarding the readme.txt it is packaged in the distributed zip file. We don't put the markdown files in the package as people are more familiar with .txt than .md, but that might change in the future.

**Comment by Hipska** [comment]
Actually, the readme.txt is already markdown format. So it might even be more clear for everyone if a file with the .md extension would be present in the package.

**Comment by Molkobain** [comment]
Hu, you are right. Then I'm clueless. Will raise the point, thanks!

**Pull request merged**
