### PR TITLE
Add "software requirements" section to README

### PR DESCRIPTION
**Pull request by Molkobain**
At first I added a complete section with a table and all currently supported versions of iTop, then @bruno-ds pointed out that it would only be redundant with the wiki page and just another source of information to maintain (which is totally true, thanks!). So instead it's just a simple link in the "resources" section.

Below is the original table, just because I learned how to make them in GitHub 😁

## Software requirements
| iTop version | PHP versions | MySQL versions | MariaDB versions | Chrome support | Firefox support | Edge support | IE support | Limitations |
|:------------:|:-------------|:---------------|:-----------------|:--------------:|:---------------:|:------------:|:----------:|:---|
| 2.8.x | **7.1-7.4** | **5.7**-8.0 | **10.3+** | ✔ | ✔ | ✔ | ❌       | - |
| 2.7.x | 5.6-7.3     | 5.6-**8.0** | 10.1+     | ✔ | ✔ | ✔ | **IE10+** | Add MySQL 8 support, but not recommended for large database |
| 2.6.1 | 5.6-**7.3** | 5.6-5.7     | 10.1+     | ✔ | ✔ | ✔ | IE9+      | Add PHP 7.3 support |
| 2.6.0 | 5.6-7.2     | 5.6-5.7     | 10.1+     | ✔ | ✔ | ✔ | IE9+      | - |

### CODE REVIEW

**Review by piRGoif — APPROVED** [review]

**Comment by Molkobain** [comment]
3 thumbs up and 1 discussion with Bruno, I'm merging it.

**Comment by Hipska** [comment]
The table looked nicer in the email notification than it does here on the web.

Oh, and the contents of it are also very nice. I don't think the wiki has such a good comparison?

**Comment by Molkobain** [comment]
@Hipska the rendering was also slightly better in the README than in the PR as well.

In the wiki, I think we could do some enhancements, what did you liked?
- Browser columns
- Min-Max versions for softwares

I can talk about it with @v-dumas

**Comment by Hipska** [comment]
The fact everything is visible in one blink of the eye. For me, the software are more important than the browsers, but both are interesting..

**Pull request merged**
