### PR TITLE
N°4511 - CKEditor : links are made on all the leading text in Firefox

### PR DESCRIPTION
**Pull request by accognet**
On Firefox, the text after @mention is the wrong color.

### CODE REVIEW

**Comment by piRGoif** [comment]
Seems like you did a CK Editor update, which version and why ?

**Comment by accognet** [comment]
Yes, it's an update to version 4.23.0 in order to have the param "followingSpace"

**Comment by Molkobain** [comment]
This has been fixed with CKEditor 5 in the `support/3.2` branch.

@v-dumas @BenGrenoble should we consider to fix it in the `support/3.1` branch or do we close this PR and the corresponding ticket?

**Comment by BenGrenoble** [comment]
This is fixed with ckeditor5 in 3.2.
We won't migrate ckeditor4 in 3.1 to avoid any regression.

**Comment by piRGoif** [comment]
Hello @Molkobain :) 
There is a "rejected" label that would better fit with the decision made than the "invalid" label you did set ?

**Comment by Molkobain** [comment]
You are right, just changed it

**Pull request closed without merging**
