### PR TITLE
add docker support

### PR DESCRIPTION
**Pull request by purplegrape**
1 add docker support just for quick deployment
2 mysql database and apcu module  not include
3 need further test and other improvemnt

add this file  for discussion

### CODE REVIEW

**Comment by purplegrape** [comment]
basic usage：
docker build -t iTop .
docker run -d -p 80:80 iTop

**Comment by Hipska** [comment]
I would not make a Docker image with a complete LAMP stack, as this is against the idea behind Docker and containerisation as principle.

**Comment by jbostoen** [comment]
If Combodo wants to include this, I think part of the debate should also be about the versions used (PHP). Personally I'd go for highest compatible and stable version.

**Comment by purplegrape** [comment]
just close it

**Pull request closed without merging**
