### PR TITLE
N°7143 Fix some old dict consistencies issues

### PR DESCRIPTION
**Pull request by piRGoif**
- french "octet" unit in the EN dict file instead of "Bytes"
- invalid br tags 
- some datamodels/2.x modules didn't have the dictionaries sub directory + a test was added (`DictionariesConsistencyTest::testNoDictFileInDatamodelsModuleRootDirectory`) to detect future files in module root dir

### CODE REVIEW

**Review by Hipska — APPROVED** [review]

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Accepted during functional review for support/3.0 event though it will only be released with 3.1.2

**Comment by piRGoif** [comment]
Rebased branch
Warning : there were 2 duplicated files : PT_BR in itop-core-update and TR in itop-welcome-itil. I handled those files manually, taking care of doing a git rename for later merges

**Comment by piRGoif** [comment]
Added a PHPUnit method to check this won't happen again !

**Review by Molkobain — APPROVED** [review]

**Comment by Molkobain** [comment]
Accepte during support PRs review.
@piRGoif will create the corresponding ticket in our bug tracker.

**Pull request merged**
