### PR TITLE
Create zh_cn.dict.itop-hub-connector.php

### PR DESCRIPTION
**Pull request by purplegrape**

### CODE REVIEW

**Comment by bruno-ds** [comment]
As the developer of iTop Hub, I have to tell you: 谢谢!

**Comment by piRGoif** [comment]
Hello,
@purplegrape, there seems to have lots of differences between your submitted file in support/2.4 and the ones in support/2.5, master or develop...
Which version should we keep ?

**Comment by purplegrape** [comment]
@piRGoif ,
I've checked the diff of the file between branch 2.4 and 2.5, 
they are almost the same except white spaces
both version are OK for me
take care , file in branch 2.5 has one more line  (line 36)

**Comment by piRGoif** [comment]
Many thanks @purplegrape !

**Pull request merged**
