### PR TITLE
:bug: Resolve JQuery error when service description is not empty

### PR DESCRIPTION
**Pull request by alally**
The addition of $(item.tooltip).text() and $(model.tooltip).text() in the service rendering twigs resulted in a jquery JS error when text was present in the description of a service. This caused the rendering of the service catalog in the portal to fail.

### CODE REVIEW

**Comment by alally** [comment]
Sorry, it looks like I made the pull request to the wrong branch.

**Comment by Hipska** [comment]
I think you could just change the brand where you want to push to here. But fine, you already created another PR.

**Comment by Molkobain** [comment]
No problem :)

**Comment by piRGoif** [comment]
Was replaced by #259

**Pull request closed without merging**
